name: smart_auth
description: Wrapper of Android SMS User Consent API, SMS Retriever API to read one time sms code, get/save/delete user phone number, OTP, OTC, sms autofill, android autofill
homepage: https://github.com/Tkko/flutter_smart_auth
repository: https://github.com/Tkko/flutter_smart_auth
topics:
  - otp
  - sms-autofill
  - sms-user-consent-api
  - sms-retriever-api
  - smart-lock
version: 1.1.1


environment:
  sdk: ">=2.16.1 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: fman.ge.smart_auth
        pluginClass: SmartAuthPlugin
      ios:
        pluginClass: SmartAuthPlugin
      linux:
        pluginClass: SmartAuthPlugin
      macos:
        pluginClass: SmartAuthPlugin
      windows:
        pluginClass: SmartAuthPlugin
      web:
        pluginClass: SmartAuthWeb
        fileName: smart_auth_web.dart